version: 2

models:
  - name: fact_stream_snapshots
    description: "Our main facts table. One row per stream, per snapshot. Built incrementally."
    columns:
      - name: stream_snapshot_id
        description: "The unique surrogate key (primary key) for the table."
        tests:
          - unique
          - not_null

      - name: viewer_count
        description: "The metric we are tracking."
        tests:
          - not_null

      - name: user_id
        description: "Foreign key to dim_streamers"
        tests:
          - not_null

      - name: game_id
        description: "Foreign key to dim_games"
        tests:
          - not_null
